app:
  name: '@project.name@'
  version: '@project.version@'
logging:
  level:
    root: INFO
server:
  error:
    whitelabel:
      enabled: false
spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    url: ${REDIS_URL}
  thymeleaf:
    cache: false
